name: tukangapptwo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.13.1
  get: 4.6.6
  flutter:
    sdk: flutter
  another_flushbar: ^1.12.30
  firebase_database: ^10.5.7
  rename_app: ^1.5.0
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  firebase_storage: ^11.7.7
  permission_handler: ^10.0.0
  fluttertoast: ^8.2.6
  file_picker: ^8.0.6
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  shared_preferences: ^2.2.3
  firebase_app_check: ^0.2.2+7
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.3
  http: ^1.2.2
  url_launcher: ^6.3.0
  logger: ^2.4.0
  intl: ^0.19.0
  flutter_rating_bar: ^4.0.1
  midtrans_sdk: ^0.4.0
  table_calendar: ^3.1.2
  # flutter_stripe: ^11.0.0

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo/logo nama white.png
    - assets/logo/
    - assets/icon/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon aplikasi.png"
  min_sdk_android: 21 # android min sdk min:16, default 21