// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2SHwGV5WkKx7VFgKPRqAOodmM_2VDM_Y',
    appId: '1:505748995222:web:4bbb388f349d29394696b7',
    messagingSenderId: '505748995222',
    projectId: 'tukangapp-876e2',
    authDomain: 'tukangapp-876e2.firebaseapp.com',
    storageBucket: 'tukangapp-876e2.appspot.com',
    measurementId: 'G-FS4NNNQTBL',
  );

  static  FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtwgez8w-uw2MSO0pnXwCxReesNVy_Xnc',
    appId: '1:505748995222:android:c4079f4442bec3804696b7',
    messagingSenderId: '505748995222',
    projectId: 'tukangapp-876e2',
    storageBucket: 'tukangapp-876e2.appspot.com',
  );

  static  FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2CL-1MrJpJQNs8aafJc1xk9c2jyXF90U',
    appId: '1:505748995222:ios:2b8a671365f2b7074696b7',
    messagingSenderId: '505748995222',
    projectId: 'tukangapp-876e2',
    storageBucket: 'tukangapp-876e2.appspot.com',
    iosBundleId: 'com.tukangapptwo.tukangapptwo',
  );

  static  FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2CL-1MrJpJQNs8aafJc1xk9c2jyXF90U',
    appId: '1:505748995222:ios:2b8a671365f2b7074696b7',
    messagingSenderId: '505748995222',
    projectId: 'tukangapp-876e2',
    storageBucket: 'tukangapp-876e2.appspot.com',
    iosBundleId: 'com.tukangapptwo.tukangapptwo',
  );

  static  FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2SHwGV5WkKx7VFgKPRqAOodmM_2VDM_Y',
    appId: '1:505748995222:web:ff707548f56617c54696b7',
    messagingSenderId: '505748995222',
    projectId: 'tukangapp-876e2',
    authDomain: 'tukangapp-876e2.firebaseapp.com',
    storageBucket: 'tukangapp-876e2.appspot.com',
    measurementId: 'G-V9FB2M0Q68',
  );
}
